### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kadiraltug** [benjaminbeilharz/Generative-Algorithms-on-CNNs#1]
I am taking error about torchsummary. 
![image](https://user-images.githubusercontent.com/57407135/183348805-8129c9bd-9850-4052-87b8-6f0753847d50.png)
I use your code directly.
![image](https://user-images.githubusercontent.com/57407135/183348888-525ca8b0-87d9-4121-84cb-937b9c786941.png)
As you can see, there is error about torchsummary. What is this problem ?

**Comment by pixelsandpointers** [comment]
Hey @kadiraltug, I guess this is due to changes on `torchsummary` side. They moved their project to [`torchinfo`](https://github.com/tyleryep/torchinfo). In the end, it does not affect the project, as you can print out the `nn.Module` to get a summary of the architecture.
