### ISSUE TITLE
Usage of code

### ISSUE THREAD

**Issue by kadiraltug** [benjaminbeilharz/Generative-Algorithms-on-CNNs#2]
Again me sir,
How can i use your code with my own data? it is only about ga.py calc_fitness function? How can i use your code on my code? Thanks.

**Comment by pixelsandpointers** [comment]
You will need to preprocess your data to a size of 32x32 + color channel since the code was written for CIFAR-10.

**Comment by kadiraltug** [comment]
I use datasets.ImageFolder instead of datasets.CIFAR10 . It is working but accuracy is so small and Loss is so high. Is there any problem or should I increase epoch size?

**Comment by pixelsandpointers** [comment]
The highest accuracy I got was 62.5, so it might be the case that, depending on your dataset it won't even achieve that much. You can definitely tune hyperparameters, but it was more an experiment than a really groundbreaking solution.

**Comment by kadiraltug** [comment]
Okey, Thanks sir

**Comment by pixelsandpointers** [comment]
Alright, happy tuning! If anything occurs, feel free to open another issue.
